### ISSUE TITLE
Entity is "null"

### ISSUE THREAD

**Issue by og-sketch12** [retrooper/packetevents#849]
**Describe the bug**
It kicks everyone and makes the server not joinable as soon as you spawn an entity let's say: zombie.

**Software brand**
Pufferfish 1.19.4

**Plugins**
ViaVersion, ProtocolLib, Matrix, Libs Disguises, MythicMobs, and alot more.

**How To Reproduce**
*Example:*
1. I'm on 1.20.1 
2. Spawn zombie with command or egg
3. And boom, you're kicked and can't join until the zombie dies

*It's fine with the old version: 2.2.1*, entity is "null"

**Comment by booky10** [comment]
we would need an error for anything to look into here, if this is even a packetevents issue
also, which packetevents version are you using here?

**Comment by Bram1903** [comment]
Probably related to: https://github.com/retrooper/packetevents/issues/803

**Comment by og-sketch12** [comment]
![image](https://github.com/retrooper/packetevents/assets/98570463/9134e0f4-d7a9-4a1b-b524-3e3db67e0754)
![image](https://github.com/retrooper/packetevents/assets/98570463/ee04ebb6-139d-4e37-b07b-860a18fa1992)
 I'm using the latest 2.3.0 version, though 2.2.1 works fine (there isnt this error) but some plugins that depend on packetevents ain't working or loading up which loads up with 2.3.0

**Comment by og-sketch12** [comment]
With the latest (as I saw in other related issues) 2.3.1-Shapshot, It says: 

[packetevents] Disconnected Shxrpness1 due to invalid packet!
[10:02:39 WARN]: io.netty.channel.StacklessClosedChannelException
[10:02:39 WARN]:        at io.netty.channel.AbstractChannel.close(ChannelPromise)(Unknown Source)
[10:02:39 WARN]: io.netty.channel.StacklessClosedChannelException
[10:02:39 WARN]:        at io.netty.channel.AbstractChannel.close(ChannelPromise)(Unknown Source)
[10:02:39 INFO]: [packetevents] Disconnected Shxrpness1 due to invalid packet!
[10:02:39 INFO]: [packetevents] Disconnected Shxrpness1 due to invalid packet!

**Comment by og-sketch12** [comment]
With the 2.2.1 version (which works but.. spamming my console with an error:

[packetevents] Unable to grab ViaVersion client version for player!

**Comment by Bram1903** [comment]
> With the 2.2.1 version (which works but.. spamming my console with an error:
> 
> 
> 
> [packetevents] Unable to grab ViaVersion client version for player!

Hello, 

That's another issue, which has been solved in a previous commit. You can use the 2.4.0-SNAPSHOT for now which should solve your ViaVersion issue: https://ci.codemc.io/job/retrooper/job/packetevents/

Kind regards,
Bram

**Comment by og-sketch12** [comment]
Some other issues have been fixed but the "entity is null" hasn't: _(I'm using 2.4.1 Sanpshot)_
![image](https://github.com/retrooper/packetevents/assets/98570463/66ff2448-2662-4387-b10e-afbbe899f314)

**Comment by og-sketch12** [comment]
Spammed my console with: (Matrix is based on packetevents, was fine with older version but doesn't work anymore with them)
![image](https://github.com/retrooper/packetevents/assets/98570463/9922f85c-805c-4e93-9f40-282cc2ea543b)

**Comment by og-sketch12** [comment]
Thanks!

**Comment by ShockCharge** [comment]
Since #905 was closed, I'll talk here instead.

These are my plugin versions:
packetevents-spigot-2.4.1-SNAPSHOT 522
ViaVersion-5.0.3-SNAPSHOT

Both of them are in the latest dev builds, and I'm still getting this error upon joining the server.

Errors:
Minecraft Client:
![image](https://github.com/user-attachments/assets/e30400ba-733c-4bcc-9b17-789b7cbac3d1)
Console:
![image](https://github.com/user-attachments/assets/abf7e33e-2404-4ec1-bd8d-090fab400042)

Therefore, updating PacketEvents to the latest dev build in Jenkins, as @Bram1903 said above, does not fix this issue.

**Comment by Bram1903** [comment]
My comment about using the latest dev build was in order to fix the ViaVersion issue where the client version couldn't be grabbed. I am pretty sure this issue is related to the synced network registries PR, which isn't yet finished / merged.

**Comment by ShockCharge** [comment]
When is this going to be fixed? It's been 3 days, and I still can't join my server

I guess I'll just remove every plugin in my server for now that needs PacketEvents to run until this gets fixed.

**Comment by ShockCharge** [comment]
> My comment about using the latest dev build was in order to fix the ViaVersion issue where the client version couldn't be grabbed. I am pretty sure this issue is related to the synced network registries PR, which isn't yet finished / merged.

Exactly @Bram1903. It is not a ViaVersion issue and if you look closely at the console error, the last message says "enchantment"
