### ISSUE TITLE
ViaVersion incompatibility?

### ISSUE THREAD

**Issue by xMrAfonso** [retrooper/packetevents#982]
**Describe the bug**
When pinging and joining the server, I get [this](https://paste.helpch.at/otuhosimos.php) error.

**Software brand**
Using Paper 1.20.6-149

**Plugins**
ViaVersion 5.0.3 (tried using snapshots of 5.0.4 and 5.0.2 but none worked either) and my own Plugin that uses PacketEvents.

**Comment by AoElite** [comment]
@xMrAfonso Are you using ViaVersion on the proxy or the backend?

**Comment by xMrAfonso** [comment]
> @xMrAfonso Are you using ViaVersion on the proxy or the backend?

I have no proxy, this is just a standalone server.

**Comment by xMrAfonso** [comment]
Any news on this?

**Comment by booky10** [comment]
works for me when using paper 1.20.6 build 149, packetevents 2bf64b610, viaversion 954 and viabackwards 494
is there any specific client version where this error occurs? do you have any other plugins installed?

**Comment by xMrAfonso** [comment]
> works for me when using paper 1.20.6 build 149, packetevents [2bf64b6](https://github.com/retrooper/packetevents/commit/2bf64b61076f9161cc3f6d704106c584602cd0c1), viaversion 954 and viabackwards 494 is there any specific client version where this error occurs? do you have any other plugins installed?

I do not, could you maybe check out my code? It's a project called Runway in my github. PS: PacketEvents version is not updated there.

**Comment by booky10** [comment]
this problem is caused by how you depend on packetevents

packetevents determines presence of viaversion by looking up if the plugin is registered
as you use the library-loader of paper plugins, your plugin (and therefore also packetevents) can't access viaversion classes and fails

there are multiple different solutions to this problem, but this cant be solved by packetevents:
1. dont use paper plugins (or set `has-open-classloader` to true, I wouldnt recommend doing this)
2. dont shade packetevents and dont use the library-loader to load it, just depend on the plugin-version of it
3. add `ViaVersion` as a non-required dependency to your paper-plugin config, therefore allowing packetevents to access its classes

**Comment by xMrAfonso** [comment]
> this problem is caused by how you depend on packetevents
> 
> packetevents determines presence of viaversion by looking up if the plugin is registered as you use the library-loader of paper plugins, your plugin (and therefore also packetevents) can't access viaversion classes and fails
> 
> there are multiple different solutions to this problem, but this cant be solved by packetevents:
> 
> 1. dont use paper plugins (or set `has-open-classloader` to true, I wouldnt recommend doing this)
> 2. dont shade packetevents and dont use the library-loader to load it, just depend on the plugin-version of it
> 3. add `ViaVersion` as a non-required dependency to your paper-plugin config, therefore allowing packetevents to access its classes

Hey, I already added ViaVersion as a soft dependency... still the same issue:
```
ViaVersion:
  load: BEFORE
  required: false
  join-classpath: true

**Comment by booky10** [comment]
See conversations on discord for some context
https://canary.discord.com/channels/721686193061888071/721686193515003966/1285549837479317555
https://canary.discord.com/channels/721686193061888071/721686193515003966/1287053524110147706
